[package]
name = "voronoi"
version = "0.1.0"
authors = ["Mark <mverleg.noreply@gmail.com>"]

[dependencies]
image = "0.19.*"
rand = "0.5.*"
threadpool = "1.7.*"
clap = "2.32.*"
byteorder = "1.2.*"
separator = "0.3.*"

[profile.release]
lto = true
# TODO remove panic to make smaller
# panic = 'abort'  # causes compile error

[lib]
name = "voronoi"
path = "src/voronoi.rs"

[[bin]]
name = "voronoi"
path = "src/main.rs"

[[bin]]
name = "voronoi-benchmark"
path = "src/benchmark.rs"
